repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.14.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
